### ISSUE TITLE
Meshconvert - ignores specular, emisive and normal textures in ExportToCMO

### ISSUE THREAD

**Issue by battlegoat** [microsoft/DirectXMesh#47]
Meshconvert / Mesh.cpp seems to output multiple textures for SDKMesh format (ExportToSDKMesh), but for the CMO format it only outputs the diffuse texture and writes blanks for all other textures (ExportToCMO  in Mesh.cpp lines 1574 ti 1583)

Since CMO as a format supports up to 8 textures per material, is there a reason for this?

(Also, ModelLoadCMO in DirectXTK only populates the diffuseTexture, but all the other material texture names are there to use).

**Comment by walbourn** [comment]
For ``meshconvert`` the exporter is very basic. The key thing is there's no good way to associate a ``.dgsl`` with a material in Wavefront OBJ, so I just use the default lambert or phong. Since those materials only support a single texture, I didn't bother to export more.

For *DirectX Tool Kit for DX11* the CMO loader takes two different paths depending on whether you provided a ``DGSLEffectFactory`` or not to the call. For the ``DGSLEffectFactory`` I provide all the defined maps.

The main issue is that other than the convention of the first texture slot in a CMO being a diffuse texture, the other 7 slots don't have any common meaning at least in the documented format. They could be specular maps, normal maps, emissive maps, alpha maps, PBR maps, bump maps, etc. The DGSL editor leaves it all up to the author of the effect to deal with that.

If you want to use the CMO material pipeline, you should use the Visual Studio content pipeline to convert your WaveFront OBJ to ``CMO`` and leverage the *DirectX Tool Kit for DX11* ``DGSLEffectFactory``.
